task:
  name: controlled

  dataset: synthetic

  batch_size: 32

  num_workers: 0

  train_size: 10000
  validation_size: 2000
  test_size: 2000

  min_nodes: 10
  max_nodes: 30

training:
  epochs: 100

  learning_rate: 0.001

  weight_decay: 0.00001

evaluation:
  seeds:
    - 0
    - 1
    - 2
    - 3
    - 4

  save_embeddings: true

  save_predictions: true
